name: Release - Build & Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'     # corre al crear tags semver (v1.2.3)
  workflow_dispatch:   # permite lanzarlo manualmente

env:
  IMAGE_NAME: devops-calculator-project
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}   # ej: sebascp368
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: release    # opcional: protege secretos/aprobaciones

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Extract version from tag
        id: v
        run: |
          ref="${GITHUB_REF##*/}"   # e.g. v1.2.3
          echo "tag=${ref}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.v.outputs.tag }}
            ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.v.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
